// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostV1PapagoDetectLangsWithBody request with any body
	PostV1PapagoDetectLangsWithBody(ctx context.Context, params *PostV1PapagoDetectLangsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1PapagoDetectLangs(ctx context.Context, params *PostV1PapagoDetectLangsParams, body PostV1PapagoDetectLangsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1PapagoN2mtWithBody request with any body
	PostV1PapagoN2mtWithBody(ctx context.Context, params *PostV1PapagoN2mtParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1PapagoN2mt(ctx context.Context, params *PostV1PapagoN2mtParams, body PostV1PapagoN2mtJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostV1PapagoDetectLangsWithBody(ctx context.Context, params *PostV1PapagoDetectLangsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1PapagoDetectLangsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1PapagoDetectLangs(ctx context.Context, params *PostV1PapagoDetectLangsParams, body PostV1PapagoDetectLangsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1PapagoDetectLangsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1PapagoN2mtWithBody(ctx context.Context, params *PostV1PapagoN2mtParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1PapagoN2mtRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1PapagoN2mt(ctx context.Context, params *PostV1PapagoN2mtParams, body PostV1PapagoN2mtJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1PapagoN2mtRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostV1PapagoDetectLangsRequest calls the generic PostV1PapagoDetectLangs builder with application/json body
func NewPostV1PapagoDetectLangsRequest(server string, params *PostV1PapagoDetectLangsParams, body PostV1PapagoDetectLangsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1PapagoDetectLangsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostV1PapagoDetectLangsRequestWithBody generates requests for PostV1PapagoDetectLangs with any type of body
func NewPostV1PapagoDetectLangsRequestWithBody(server string, params *PostV1PapagoDetectLangsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/papago/detectLangs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XNaverClientId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Naver-Client-Id", runtime.ParamLocationHeader, *params.XNaverClientId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Naver-Client-Id", headerParam0)
		}

		if params.XNaverClientSecret != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-Naver-Client-Secret", runtime.ParamLocationHeader, *params.XNaverClientSecret)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Naver-Client-Secret", headerParam1)
		}

	}

	return req, nil
}

// NewPostV1PapagoN2mtRequest calls the generic PostV1PapagoN2mt builder with application/json body
func NewPostV1PapagoN2mtRequest(server string, params *PostV1PapagoN2mtParams, body PostV1PapagoN2mtJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1PapagoN2mtRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostV1PapagoN2mtRequestWithBody generates requests for PostV1PapagoN2mt with any type of body
func NewPostV1PapagoN2mtRequestWithBody(server string, params *PostV1PapagoN2mtParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/papago/n2mt")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XNaverClientId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Naver-Client-Id", runtime.ParamLocationHeader, *params.XNaverClientId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Naver-Client-Id", headerParam0)
		}

		if params.XNaverClientSecret != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-Naver-Client-Secret", runtime.ParamLocationHeader, *params.XNaverClientSecret)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Naver-Client-Secret", headerParam1)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostV1PapagoDetectLangsWithBodyWithResponse request with any body
	PostV1PapagoDetectLangsWithBodyWithResponse(ctx context.Context, params *PostV1PapagoDetectLangsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1PapagoDetectLangsResponse, error)

	PostV1PapagoDetectLangsWithResponse(ctx context.Context, params *PostV1PapagoDetectLangsParams, body PostV1PapagoDetectLangsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1PapagoDetectLangsResponse, error)

	// PostV1PapagoN2mtWithBodyWithResponse request with any body
	PostV1PapagoN2mtWithBodyWithResponse(ctx context.Context, params *PostV1PapagoN2mtParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1PapagoN2mtResponse, error)

	PostV1PapagoN2mtWithResponse(ctx context.Context, params *PostV1PapagoN2mtParams, body PostV1PapagoN2mtJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1PapagoN2mtResponse, error)
}

type PostV1PapagoDetectLangsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DetectedLangs
}

// Status returns HTTPResponse.Status
func (r PostV1PapagoDetectLangsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1PapagoDetectLangsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1PapagoN2mtResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Message
}

// Status returns HTTPResponse.Status
func (r PostV1PapagoN2mtResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1PapagoN2mtResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostV1PapagoDetectLangsWithBodyWithResponse request with arbitrary body returning *PostV1PapagoDetectLangsResponse
func (c *ClientWithResponses) PostV1PapagoDetectLangsWithBodyWithResponse(ctx context.Context, params *PostV1PapagoDetectLangsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1PapagoDetectLangsResponse, error) {
	rsp, err := c.PostV1PapagoDetectLangsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1PapagoDetectLangsResponse(rsp)
}

func (c *ClientWithResponses) PostV1PapagoDetectLangsWithResponse(ctx context.Context, params *PostV1PapagoDetectLangsParams, body PostV1PapagoDetectLangsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1PapagoDetectLangsResponse, error) {
	rsp, err := c.PostV1PapagoDetectLangs(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1PapagoDetectLangsResponse(rsp)
}

// PostV1PapagoN2mtWithBodyWithResponse request with arbitrary body returning *PostV1PapagoN2mtResponse
func (c *ClientWithResponses) PostV1PapagoN2mtWithBodyWithResponse(ctx context.Context, params *PostV1PapagoN2mtParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1PapagoN2mtResponse, error) {
	rsp, err := c.PostV1PapagoN2mtWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1PapagoN2mtResponse(rsp)
}

func (c *ClientWithResponses) PostV1PapagoN2mtWithResponse(ctx context.Context, params *PostV1PapagoN2mtParams, body PostV1PapagoN2mtJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1PapagoN2mtResponse, error) {
	rsp, err := c.PostV1PapagoN2mt(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1PapagoN2mtResponse(rsp)
}

// ParsePostV1PapagoDetectLangsResponse parses an HTTP response from a PostV1PapagoDetectLangsWithResponse call
func ParsePostV1PapagoDetectLangsResponse(rsp *http.Response) (*PostV1PapagoDetectLangsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1PapagoDetectLangsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DetectedLangs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostV1PapagoN2mtResponse parses an HTTP response from a PostV1PapagoN2mtWithResponse call
func ParsePostV1PapagoN2mtResponse(rsp *http.Response) (*PostV1PapagoN2mtResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1PapagoN2mtResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Message
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
