// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package openapi

// DetectedLangs defines model for detectedLangs.
type DetectedLangs struct {
	LangCode *string `json:"langCode,omitempty"`
}

// Message defines model for message.
type Message struct {
	Message *struct {
		Service *string `json:"@service,omitempty"`
		Type    *string `json:"@type,omitempty"`
		Version *string `json:"@version,omitempty"`
		Result  *Result `json:"result,omitempty"`
	} `json:"message,omitempty"`
}

// QueryWord defines model for queryWord.
type QueryWord struct {
	Query string `json:"query"`
}

// Result defines model for result.
type Result struct {
	SrcLangType    *string `json:"srcLangType,omitempty"`
	TarLangType    *string `json:"tarLangType,omitempty"`
	TranslatedText *string `json:"translatedText,omitempty"`
}

// PostV1PapagoDetectLangsParams defines parameters for PostV1PapagoDetectLangs.
type PostV1PapagoDetectLangsParams struct {
	XNaverClientId     *string `json:"X-Naver-Client-Id,omitempty"`
	XNaverClientSecret *string `json:"X-Naver-Client-Secret,omitempty"`
}

// PostV1PapagoN2mtJSONBody defines parameters for PostV1PapagoN2mt.
type PostV1PapagoN2mtJSONBody struct {
	Source string `json:"source"`
	Target string `json:"target"`
	Text   string `json:"text"`
}

// PostV1PapagoN2mtParams defines parameters for PostV1PapagoN2mt.
type PostV1PapagoN2mtParams struct {
	XNaverClientId     *string `json:"X-Naver-Client-Id,omitempty"`
	XNaverClientSecret *string `json:"X-Naver-Client-Secret,omitempty"`
}

// PostV1PapagoDetectLangsJSONRequestBody defines body for PostV1PapagoDetectLangs for application/json ContentType.
type PostV1PapagoDetectLangsJSONRequestBody = QueryWord

// PostV1PapagoN2mtJSONRequestBody defines body for PostV1PapagoN2mt for application/json ContentType.
type PostV1PapagoN2mtJSONRequestBody PostV1PapagoN2mtJSONBody
